import { User, Product } from '../types';
import { v4 as uuidv4 } from 'uuid';

// Initial admin user has been removed
export const initialUsers: User[] = [];

// Sample product data - Gaming focused
export const initialProducts: Product[] = [
  {
    id: uuidv4(),
    name: 'Gaming Headset Pro X',
    description: 'Professional gaming headset with 7.1 surround sound, noise-cancelling microphone and RGB lighting. Perfect for competitive gaming.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/7915535/pexels-photo-7915535.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 25,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Mechanical Gaming Keyboard',
    description: 'RGB mechanical keyboard with customizable keycaps and programmable macros. Features durable switches with 50 million keystroke lifespan.',
    price: 129.99,
    imageUrl: 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 15,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Elite Gaming Mouse',
    description: 'High-precision gaming mouse with 16,000 DPI optical sensor, customizable weight, and 8 programmable buttons.',
    price: 69.99,
    imageUrl: 'https://images.pexels.com/photos/5483064/pexels-photo-5483064.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 20,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Ultra-wide Gaming Monitor',
    description: '34-inch curved ultra-wide gaming monitor with 144Hz refresh rate, 1ms response time, and G-Sync compatibility for smooth gameplay.',
    price: 449.99,
    imageUrl: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 8,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming PC Case',
    description: 'Mid-tower gaming case with tempered glass side panel, excellent airflow design, and pre-installed RGB fans.',
    price: 99.99,
    imageUrl: 'https://images.pexels.com/photos/2225617/pexels-photo-2225617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 12,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Limited Edition Console Controller',
    description: 'Special edition wireless game controller with programmable back buttons, improved joysticks and customizable faceplates.',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/4219883/pexels-photo-4219883.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 10,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'High-Performance Gaming GPU',
    description: 'Latest generation graphics card with 12GB VRAM, ray tracing capabilities, and advanced cooling system for maximum performance.',
    price: 799.99,
    imageUrl: 'https://images.pexels.com/photos/1034651/pexels-photo-1034651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 5,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'RGB Gaming Desk Mat',
    description: 'Extra large desk mat with RGB edges, smooth surface for precise mouse tracking, and non-slip rubber base.',
    price: 34.99,
    imageUrl: 'https://images.pexels.com/photos/7654586/pexels-photo-7654586.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 30,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Pro Gaming Headphone Stand',
    description: 'Aluminum headphone stand with RGB lighting and 2 USB ports. Keep your gaming setup organized and your headset on display.',
    price: 39.99,
    imageUrl: 'https://images.pexels.com/photos/5082577/pexels-photo-5082577.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 18,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Wireless Charging Gaming Mouse',
    description: 'Ultralight gaming mouse with wireless charging, 25,000 DPI sensor, and 70-hour battery life. Never worry about cables again.',
    price: 129.99,
    imageUrl: 'https://images.pexels.com/photos/1337247/pexels-photo-1337247.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 14,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming CPU - 12 Core',
    description: 'High-performance gaming CPU with 12 cores, 24 threads, and up to 5.2GHz boost clock. Perfect for gaming and content creation.',
    price: 549.99,
    imageUrl: 'https://images.pexels.com/photos/3520694/pexels-photo-3520694.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 7,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming RAM - 32GB RGB',
    description: '32GB DDR5 gaming RAM with RGB lighting, CL16 timing, and overclocking capabilities up to 6000MHz.',
    price: 189.99,
    imageUrl: 'https://images.pexels.com/photos/2588757/pexels-photo-2588757.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 22,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Motherboard Z790',
    description: 'High-end gaming motherboard with PCIe 5.0, WiFi 6E, and enhanced power delivery for maximum overclocking potential.',
    price: 329.99,
    imageUrl: 'https://images.pexels.com/photos/163140/technology-computer-motherboard-desktop-163140.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 9,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming SSD 2TB',
    description: 'Ultra-fast 2TB NVMe SSD with 7000MB/s read speeds. Reduce game loading times and improve system responsiveness.',
    price: 229.99,
    imageUrl: 'https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 16,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Power Supply - 1000W Platinum',
    description: '1000W Platinum-rated fully modular power supply with silent operation and Japanese capacitors for gaming PCs.',
    price: 199.99,
    imageUrl: 'https://images.pexels.com/photos/5060426/pexels-photo-5060426.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 11,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Streaming Microphone',
    description: 'Professional studio-quality gaming microphone with RGB lighting, shock mount, and four polar patterns for streaming and content creation.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/6671723/pexels-photo-6671723.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 13,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Stream Deck',
    description: '15-key customizable LCD keypad for streamers and content creators. Control your stream, launch apps, and more with a single touch.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/4791474/pexels-photo-4791474.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 8,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: '4K Gaming Capture Card',
    description: 'Capture and stream your gameplay in 4K at 60fps with this plug-and-play capture card. Compatible with consoles and PC.',
    price: 179.99,
    imageUrl: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 12,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'VR Gaming Headset',
    description: 'Immersive virtual reality headset with 4K resolution per eye, 120Hz refresh rate, and advanced motion tracking for the ultimate gaming experience.',
    price: 499.99,
    imageUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 6,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Glasses - Blue Light Filter',
    description: 'Protect your eyes during long gaming sessions with these stylish glasses that filter harmful blue light from screens.',
    price: 49.99,
    imageUrl: 'https://images.pexels.com/photos/5240511/pexels-photo-5240511.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 25,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Hoodie - Pro Team Edition',
    description: 'Official gaming team hoodie with embroidered logo, premium fabric, and hidden earbud routing for the ultimate gaming comfort.',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/5082567/pexels-photo-5082567.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Clothing',
    stock: 20,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Backpack',
    description: 'Water-resistant gaming backpack with hardshell protection, dedicated laptop compartment, and multiple accessory pockets for all your gear.',
    price: 89.99,
    imageUrl: 'https://images.pexels.com/photos/1294731/pexels-photo-1294731.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 18,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Smartphone Controller',
    description: 'Turn your smartphone into a gaming console with this ergonomic controller that attaches directly to your phone for superior mobile gaming.',
    price: 59.99,
    imageUrl: 'https://images.pexels.com/photos/3945673/pexels-photo-3945673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 23,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Web Camera 4K',
    description: '4K webcam with 60fps, autofocus, and built-in ring light for streamers and content creators. Make your streams look professional.',
    price: 129.99,
    imageUrl: 'https://images.pexels.com/photos/4404515/pexels-photo-4404515.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 15,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Hand Grip Strengthener',
    description: 'Improve your gaming performance with this adjustable resistance hand trainer designed for gamers. Reduce fatigue during long sessions.',
    price: 19.99,
    imageUrl: 'https://images.pexels.com/photos/4571151/pexels-photo-4571151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 30,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Mini Refrigerator',
    description: 'Keep your drinks cold during intense gaming sessions with this 10L mini fridge. Features RGB lighting and USB charging port.',
    price: 99.99,
    imageUrl: 'https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 10,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'LED Gaming Room Strips',
    description: 'Transform your gaming room with these smart LED light strips. Sync with your games for immersive ambient lighting effects.',
    price: 49.99,
    imageUrl: 'https://images.pexels.com/photos/2662116/pexels-photo-2662116.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 28,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Monitor Mount - Dual',
    description: 'Dual monitor mount with gas spring arms for effortless adjustments. Free up desk space and position your gaming displays perfectly.',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/1712058/pexels-photo-1712058.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 19,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'USB Gaming Hub',
    description: '10-port USB hub with individual power switches and LED indicators. Perfect for connecting all your gaming peripherals.',
    price: 39.99,
    imageUrl: 'https://images.pexels.com/photos/4200069/pexels-photo-4200069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 24,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Chair - Pro Series',
    description: 'Ergonomic gaming chair with 4D armrests, reclining backrest, and memory foam cushions for maximum comfort during long gaming sessions.',
    price: 299.99,
    imageUrl: 'https://images.pexels.com/photos/7915574/pexels-photo-7915574.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Furniture',
    stock: 14,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Desk - RGB',
    description: 'Carbon fiber textured gaming desk with built-in RGB lighting, cable management, and cup holder. The ultimate gaming battlestation.',
    price: 249.99,
    imageUrl: 'https://images.pexels.com/photos/777001/pexels-photo-777001.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Furniture',
    stock: 8,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Collectible Gaming Figurine - Limited Edition',
    description: 'Hand-painted limited edition collectible figurine from your favorite game. A must-have for serious collectors.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/1422673/pexels-photo-1422673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Collectibles',
    stock: 5,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Notebook - Special Edition',
    description: 'Premium hardcover gaming notebook with character artwork, grid pages, and bookmark. Perfect for game planning and notes.',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/3829227/pexels-photo-3829227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Collectibles',
    stock: 27,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Strategy Guide - Collector\'s Edition',
    description: 'Hardcover collector\'s edition strategy guide with exclusive artwork, detailed maps, and advanced tactics for the serious gamer.',
    price: 39.99,
    imageUrl: 'https://images.pexels.com/photos/160913/bookshelf-education-homework-books-160913.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Collectibles',
    stock: 15,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Mouse Bungee',
    description: 'Keep your mouse cord off your desk with this sturdy mouse bungee. Flexible arm design allows free movement while preventing cable drag.',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/7004743/pexels-photo-7004743.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 22,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming PC - Ultimate Edition',
    description: 'Pre-built gaming PC with top-of-the-line components. Features the latest CPU, GPU, 32GB RAM, and 2TB SSD. Ready for any game.',
    price: 2499.99,
    imageUrl: 'https://images.pexels.com/photos/1591060/pexels-photo-1591060.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 3,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Laptop - 17" Beast',
    description: '17-inch gaming laptop with desktop-class performance. Features 240Hz display, mechanical keyboard, and advanced cooling system.',
    price: 1999.99,
    imageUrl: 'https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 6,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Sound Card',
    description: 'Audiophile-grade sound card for gaming with virtual 7.1 surround sound, high-res 192kHz/24-bit audio, and customizable EQ profiles.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/2114365/pexels-photo-2114365.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 9,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Network Card - WiFi 6E',
    description: 'Ultra-fast WiFi 6E network card with Bluetooth 5.2 for lag-free online gaming. Includes advanced heat sink for sustained performance.',
    price: 89.99,
    imageUrl: 'https://images.pexels.com/photos/163073/ethernet-cable-ethernet-cable-network-internet-163073.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 13,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Cooling System',
    description: 'Advanced liquid cooling system for your gaming PC with RGB lighting and temperature display. Keep your hardware cool under pressure.',
    price: 179.99,
    imageUrl: 'https://images.pexels.com/photos/2225617/pexels-photo-2225617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 7,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming External SSD - 1TB',
    description: 'Portable 1TB SSD with read speeds up to 2000MB/s. Store and play your games from anywhere with this compact drive.',
    price: 149.99,
    imageUrl: 'https://images.pexels.com/photos/4390119/pexels-photo-4390119.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 16,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Mechanical Keyboard Switch Tester',
    description: 'Test 9 different types of mechanical switches before buying your keyboard. Find the perfect switch for your gaming style.',
    price: 19.99,
    imageUrl: 'https://images.pexels.com/photos/667899/pexels-photo-667899.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 25,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Mouse Grip Tape',
    description: 'Premium grip tape for gaming mice. Improve control and comfort during intense gaming sessions with these pre-cut sheets.',
    price: 12.99,
    imageUrl: 'https://images.pexels.com/photos/1420709/pexels-photo-1420709.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 40,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Console - Premium Bundle',
    description: 'Latest gaming console bundle with two controllers, three games, and online subscription. Everything you need to start gaming.',
    price: 599.99,
    imageUrl: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 8,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Premium Gaming Controller - Pro',
    description: 'Professional-grade gaming controller with adjustable triggers, customizable paddles, and premium thumbsticks for competitive play.',
    price: 179.99,
    imageUrl: 'https://images.pexels.com/photos/696644/pexels-photo-696644.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 12,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Foot Pedal Controller',
    description: 'Triple pedal controller for gaming that adds extra inputs for your feet. Perfect for simulation games and shortcuts.',
    price: 79.99,
    imageUrl: 'https://images.pexels.com/photos/6243737/pexels-photo-6243737.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 9,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Poster - Limited Edition',
    description: 'Limited edition gaming poster signed by the development team. Printed on premium paper with metallic ink accents.',
    price: 49.99,
    imageUrl: 'https://images.pexels.com/photos/1509534/pexels-photo-1509534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Collectibles',
    stock: 7,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Retro Gaming Console',
    description: 'Miniature replica of a classic gaming console with 30 pre-loaded games. Plug and play on any HDMI TV for instant nostalgia.',
    price: 99.99,
    imageUrl: 'https://images.pexels.com/photos/442576/pexels-photo-442576.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Hardware',
    stock: 14,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Earbuds - Low Latency',
    description: 'Wireless gaming earbuds with ultra-low latency, noise cancellation, and 12-hour battery life. Perfect for mobile gaming.',
    price: 89.99,
    imageUrl: 'https://images.pexels.com/photos/3394666/pexels-photo-3394666.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 17,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Wrist Rest - Memory Foam',
    description: 'Ergonomic memory foam wrist rest with cooling gel and anti-slip base. Reduce strain during long gaming sessions.',
    price: 24.99,
    imageUrl: 'https://images.pexels.com/photos/4195409/pexels-photo-4195409.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 25,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Gaming Keycap Set - Custom',
    description: 'Custom keycap set for mechanical keyboards with double-shot PBT construction and gaming-themed designs.',
    price: 59.99,
    imageUrl: 'https://images.pexels.com/photos/1772123/pexels-photo-1772123.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Accessories',
    stock: 20,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Digital Game Gift Card - $50',
    description: '$50 gift card for the digital game store of your choice. Perfect gift for gamers to buy new releases or DLC.',
    price: 50.00,
    imageUrl: 'https://images.pexels.com/photos/6956183/pexels-photo-6956183.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Games',
    stock: 100,
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Game Subscription - 12 Month',
    description: '12-month subscription to premium game service with access to over 100 games, exclusive discounts, and online multiplayer.',
    price: 119.99,
    imageUrl: 'https://images.pexels.com/photos/1174746/pexels-photo-1174746.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    category: 'Games',
    stock: 50,
    createdAt: new Date(),
  }
];

// Categories
export const categories = [
  'All',
  'Hardware',
  'Accessories',
  'Games',
  'Collectibles',
  'Furniture',
  'Clothing'
];